### ISSUE TITLE
Status of the project ?

### ISSUE THREAD

**Issue by AkechiShiro** [Orange-Cyberdefense/bof#16]
First of all, thanks for building this framework but there weren't much updates of lately.

Is the project unmaintained at the moment?

**Comment by claire-lex** [comment]
Hi, 

The project is still ongoing however I am currently alone to work on it, that's why it's slow at the moment.
The next updates will probably be related to the network discovery part, I am willing to add discovery functions for more protocols.

If you want the last updates, you can switch to the "dev" branch. Currently, it's quite similar to the main branch because the release is not very old, but usually it is the most up-to-date branch (but it is also more unstable). 

I hope this answers your question. Of course you are welcome to contribute if you want to!
